$script = <<-SHELL
wget https://apt.puppetlabs.com/puppet6-release-bionic.deb
sudo dpkg -i puppet6-release-bionic.deb
sudo apt-get update
sudo apt-get install -y puppet-agent
SHELL

Vagrant.configure(2) do |config|

    config.vm.define "puppetApache" do |puppetApache|
        puppetApache.vm.box = "ubuntu/bionic64"
        puppetApache.vm.network "private_network", ip: "192.168.33.10"
        puppetApache.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.name = "puppetApache"
        end
        puppetApache.vm.provision "shell", inline: $script
        puppetApache.vm.provision "puppet" do |puppet|
            puppet.module_path = "modules" # Default
            puppet.manifests_path = "manifests" # Default
            puppet.manifest_file = "default.pp" # Default
        end
    end
end
 