$scipt = <<-SHELL


SHELL

Vagrant.configure("2") do |config|
  config.vm.define "WordPressVM" do |wordPress|
    wordPress.vm.box = "ubuntu/bionic64"
    wordPress.vm.network "private_network", ip: "192.168.33.10"
    wordPress.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "WordPressVM"
    end
  end
    #wordPress.vm.provision "puppet" do |puppet|
end
